inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - spec/fixtures/**/*
    - tmp/**/*
    - config/environments/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
